### ISSUE TITLE
Update installation section of the README

### ISSUE THREAD

**Issue by avoltmer** [terraform-providers/terraform-provider-nsxt#1]
The installation section was written for manual install of the provider. It now automatically installs using "terraform init". This section of the documentation needs to be updated to reflect the fact that the provider is now part of the Terraform ecosystem.

**Comment by vancluever** [comment]
@avoltmer yeah, I think we should probably just wholesale update this README to a more general one. I'm going to boilerplate it off of the vSphere provider one, with some edits.

Thanks!
