### ISSUE TITLE
DHCP server IP pools feature not present.

### ISSUE THREAD

**Issue by kirandevraaj** [terraform-providers/terraform-provider-nsxt#115]
Terraform Version and vSphere Provider Version

vmware@rallyrunner:~/go/bin$ ./terraform version
Terraform v0.11.8
+ provider.nsxt (unversioned)
+ provider.vsphere v1.8.1

type=feature
Affected Resource(s) - nsxt_logical_dhcp_server

While adding DHCP server/update the DHCP server, there is no way to add ip pool for the DHCP service. Currently we need to add ip pool manually to the dhcp server, for client vm to get fixed ip.

The NSX api that we will need to support is POST /api/v1/dhcp/servers/<id> /ip-pools

**Comment by annakhm** [comment]
Thanks for reporting this!
Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/116
