### ISSUE TITLE
Manage VMware NSX-T infrastucture from behind proxy.

### ISSUE THREAD

**Issue by bhadrim** [terraform-providers/terraform-provider-nsxt#119]
I am trying to manage VMware NSX-T infrastructure from a system that allows outbound http/https connections using a proxy server. This fails with the following error 

error(s) occurred:* provider.nsxt: Failed to create session: Post https://xxx/api/session/create: dial tcp xxx:443: getsockopt: no route to host.

It looks like the https://github.com/terraform-providers/terraform-provider-nsxt/blob/master/vendor/github.com/vmware/go-vmware-nsxt/api_client.go#L180 is missing Proxy: http.ProxyFromEnvironment. I am able to get it to work after I change the code to 

transport := &http.Transport{Proxy: http.ProxyFromEnvironment,TLSClientConfig: tlsConfig}

**Comment by annakhm** [comment]
Thanks for reporting this! Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/120

**Comment by annakhm** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/122

**Comment by bhadrim** [comment]
@annakhm Thank you for fixing this issue. Do you know when this fix will be released. I ran a terraform template that uses nsxt today and terraform pulled the 1.0.0 plugin (which do not have this fix). Thank you.

**Comment by annakhm** [comment]
@bhadrim next release is planned in January as far as I know

**Comment by bhadrim** [comment]
@annakhm @avoltmer Thank you for the information.
