### ISSUE TITLE
The ability to specify a VLAN LS with VLAN ID: 0

### ISSUE THREAD

**Issue by nvpnathan** [terraform-providers/terraform-provider-nsxt#128]
1 error(s) occurred:

* nsxt_logical_switch.T0_UPLINK_VLAN_LS: 1 error(s) occurred:

* nsxt_logical_switch.T0_UPLINK_VLAN_LS: Error during LogicalSwitch create: Status: 400 , Body: {
 "httpStatus" : "BAD_REQUEST",
 "error_code" : 8318,
 "module_name" : "NsxSwitching service",
 "error_message" : "The VLAN field must be specified in the logical switch configuration for logical switches in the VLAN Transport Zone."
}

**Comment by annakhm** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/131
