### ISSUE TITLE
After "terraform apply" it will try and update the "failover_mode "" => PREEMPTIVE on T1 routers

### ISSUE THREAD

**Issue by nvpnathan** [terraform-providers/terraform-provider-nsxt#129]
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ nsxt_logical_tier1_router.T1-K8S
      failover_mode:    "" => "PREEMPTIVE"

  ~ nsxt_logical_tier1_router.T1-MGMT
      failover_mode:    "" => "PREEMPTIVE"

If you submit another terraform apply it will try an update the T1 routers again even if nothing has changed.

**Comment by annakhm** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/139
