### ISSUE TITLE
After "terraform apply" it will try and update logical switches "replication_mode" => MTEP

### ISSUE THREAD

**Issue by nvpnathan** [terraform-providers/terraform-provider-nsxt#130]
Terraform will perform the following actions:

  ~ nsxt_logical_switch.T0_UPLINK_VLAN_LS
      replication_mode: "" => "MTEP"

If you submit another terraform apply it will try an update the LS with the replication mode again if nothing in the template has changed.

**Comment by annakhm** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/131
Please use new resource nsxt_vlan_logical_switch for vlan LS
