### ISSUE TITLE
Please release a current version of the NSX-T provider

### ISSUE THREAD

**Issue by cunnie** [terraform-providers/terraform-provider-nsxt#141]
Hello esteemed maintainers,

Could you please release a current version of the NSX-T provider? We would like to take advantage of the as-yet unreleased load balancer features. Thanks!

**Comment by tvigneron** [comment]
Hello cunnie,
We map the Terraform Provider release to GA version of NSX-T as this provider is supported by VMware. The next version will be released with NSX-T and offered both on VMware download page and via "terraform init".
If you want to take advantage of specific features before, you can build manually the provider from the GitHub page: https://github.com/terraform-providers/terraform-provider-nsxt. (This is not supported though)

**Comment by cunnie** [comment]
Thanks @tvigneron ! I will close this issue because you've answered my question.

**Comment by tvigneron** [comment]
@cunnie We have released the version upstream. You can pick it on via HashiCorp
