### ISSUE TITLE
Firewall section always modifies even when no changes are made - Services and AppliedTo

### ISSUE THREAD

**Issue by dcoghlan** [terraform-providers/terraform-provider-nsxt#151]
Somewhat similar to #107, this also occurs when multiple services are specified in a rule.

And to make sure that nothing is left out, the other field that can return multiple entries is the Applied To field of a rule.

Found the issue while using version 1.1.0 of the NSX-T Provider.

**Comment by annakhm** [comment]
Thanks for filing this. Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/156
