### ISSUE TITLE
Create uplink router port for t0 router

### ISSUE THREAD

**Issue by rahulkj** [terraform-providers/terraform-provider-nsxt#160]
I'm having a hard time to find the right resource to create an UPLINK router port for t0 router. All I see is centralized `nsxt_logical_router_centralized_service_port` and downlink `nsxt_logical_router_downlink_port`

How do I create the uplink port?

**Comment by annakhm** [comment]
Hi @rahulkj, unfortunately not supported yet

**Comment by rahulkj** [comment]
I figured. So for now I will keep it as a manual task, but do you have any timeframe by which this will be addressed @annakhm

**Comment by tvigneron** [comment]
Hello Rahul,
We are planning to extend NSX-T logical construct consumption around the new Policy API. 
This will encompass the T-0 and offer the ability to have an uplink.  The current plan today is around end of the year.

**Comment by tonytjo** [comment]
Dear @tvigneron,

Is it any update on "consumption the new Policy API"?

Thanks a lot.

Regards,
Tony

**Comment by tvigneron** [comment]
Hello Tonytjo,
This is being worked on and should appear very soon on the GitHub. 
We are finalizing the paperwork to have it publicly available.
Thomas

**Comment by tonytjo** [comment]
Dear @tvigneron,

Thanks a lot for your prompt update!!

Regards,
Tony

**Comment by annakhm** [comment]
Hello, 
uplink router port can now be configured with nsxt_policy_tier0_gateway_interface. This functionality is not yet released but is available if you compile the provider. Hope this helps

**Comment by walbertus** [comment]
So you won't support uplink router port using non-policy API?
Can I combine nsxt_policy_tier0_gateway_interface with tier0 router created with nsxt_logical_tier0_router?

**Comment by annakhm** [comment]
Hi @walbertus, there is currently no plan to support uplink with non-policy API.
Objects that are created via non-policy API are not visible on policy level, so you won't be able to use policy feature for non-policy resource. However, the other way around works.
