### ISSUE TITLE
Terraform breaks when NAT rule is deleted

### ISSUE THREAD

**Issue by z4ce** [terraform-providers/terraform-provider-nsxt#165]
# Expected behavior
When a previously created  NAT rule is deleted and `terraform apply` is run, the NAT rule is recreated.

# Observed behavior
When a previously created  NAT rule is deleted and `terraform apply` is run, terraform produces an error and refuses to continue. Produces error like this:
```
Error: Error refreshing state: 1 error(s) occurred:

* nsxt_nat_rule.pks-dnat-api: 1 error(s) occurred:

* nsxt_nat_rule.pks-dnat-api: nsxt_nat_rule.pks-dnat-api: Error during NatRule read: Status: 400 , Body: {
  "httpStatus" : "BAD_REQUEST",
  "error_code" : 11013,
  "module_name" : "ROUTING",
  "error_message" : "[Routing] Invalid resource NAT rule 1064 for the logical router 8b6dbd75-4820-426c-b754-abf0ae62102a."
}
```

# Steps to reproduce
1. Create terraform that requires a NAT rule
2. Run `terraform apply` against NSX-T
3. Delete the NAT rule using the NSX-Manager GUI
4. Run `terraform apply`

**Comment by annakhm** [comment]
Hi @z4ce, thanks for reporting this issue! Could you please provide your config, and NSXT version. The general case of deleting nat rule works for us. Thanks!

**Comment by z4ce** [comment]
Hi @annakhm,  I can confirm that Terraform can delete a NAT rule just fine. In this case the NAT rule is being deleted directly using the NSX-Manager GUI. I'm expecting Terraform to recreate the externally deleted NAT rule.  I'll update my steps to reproduce to make that more clear. The version if NSXT we are using is 2.3.1.  What config would help?

**Comment by annakhm** [comment]
Thanks for the detailed explanation, fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/166

**Comment by z4ce** [comment]
Thanks for the super quick resolution! Any idea when you'll cut the next release?

**Comment by annakhm** [comment]
Unfortunately release plan is not finalized yet. Hope we'll release the bugfix release soon!
