### ISSUE TITLE
Support for terraform cli 0.12.0

### ISSUE THREAD

**Issue by rahulkj** [terraform-providers/terraform-provider-nsxt#167]
Is there any plans for providing support for terraform cli 0.12.0?

I ran into the issue, where `brew` installed terraform version `0.12.0`, and my `terraform init` started to fail.

Upon scanning the release notes from hashicorp, I ran into this https://www.hashicorp.com/blog/releasing-terraform-0-12-0-rc1#provider-compatibility

and NSX-T is not available as a provider there.

**Comment by annakhm** [comment]
Hi @rahulkj, the provider was aligned with 0.12 but not yet released. Sorry I can't update on release estimate yet.

**Comment by rahulkj** [comment]
Terraform cli has the new command `0.12upgrade`. I used that to upgrade my NSX-T terraform code, and now its working fine with terraform version `0.12.x`

**Comment by annakhm** [comment]
Thanks for the feedback!
