### ISSUE TITLE
Change pre-created object tags

### ISSUE THREAD

**Issue by hakkurt** [terraform-providers/terraform-provider-nsxt#170]
Is there any way to change pre-created NSX-T object tag via TF ?

**Comment by annakhm** [comment]
Hi @hakkurt, can you please give an example of such pre-created tag?

**Comment by hakkurt** [comment]
Hi. I'm trying to automate NSX-T and vanilla K8S integration via TF. There are some steps needs to tag NSX-T objects (like existing transport zones, logical ports) with_k8s-cluster1 ncp/cluster_ tag. I can tag NSX-T objects if I create them via TF but if the object is created manually, I could not find a way to tag them.

**Comment by annakhm** [comment]
Hi, you can import the existing logical port into terraform and then manage the tags, but this will not work with TZs since these are not offered as provider resource at this point.

**Comment by hakkurt** [comment]
The problem is : I must know object id to use import function. Logical ports are created after VMs are connected to to logical ports. This operation is also done in my TF file. My TF files are located at https://github.com/hakkurt/Terraform/tree/master/NSXT-K8S .Could you please give me an advice on how to do that ?

**Comment by tvigneron** [comment]
Hello Hakkurt, 
A solution I see would be to tag your VMs and use Apply To (by Logical Switch for instance) on the Distributed Firewall. 
This way you'll be able to achieve the same result but will not have wait to know port object id.

**Comment by tvigneron** [comment]
Would that work for you ?

**Comment by hakkurt** [comment]
Hi Thomas,
Actually I'm trying to tag logical ports for K8S NCP integration. To be honest, I could not get how tagging VMs will help to achieve this :)

**Comment by annakhm** [comment]
Hi @hakkurt, sounds like you need a resource similar to nsxt_vm_tags, only for port tags, to be used to tag auto-created ports. We'll look into this, thanks for reporting the need!

**Comment by annakhm** [comment]
Hi @hakkurt, we've added an option to set port tags via nsxt_vm_tags resource here:
https://github.com/terraform-providers/terraform-provider-nsxt/pull/171
Pls let us know if this works for you! Thanks

**Comment by hakkurt** [comment]
Thanks for the improvement. In fact, my request was about tagging NSX-T logical ports not VMs. Can I do following steps by using this TF resource ?
https://github.com/dumlutimuralp/nsx-t-k8s/blob/master/Part%203/README.md#tagging-nsx-t-objects-for-k8s

Thanks

**Comment by annakhm** [comment]
yes, now you can use attribute logical_port_tag of nsxt_vm_tags resource, and the provider will apply these tags to logical port that corresponds to the VM

**Comment by hakkurt** [comment]
I have just tested. Its tagging VM itself not Logical ports. Pls see screenshoots

![1](https://user-images.githubusercontent.com/23055580/60327699-df292e80-998c-11e9-9711-d0b880f2f21b.PNG)

![2](https://user-images.githubusercontent.com/23055580/60327754-fe27c080-998c-11e9-83e6-bac3ca6cdfb2.PNG)

**Comment by annakhm** [comment]
@hakkurt sorry just to confirm - you are setting logical_port_tag (not tag) attribute on nsxt_vm_tags, with master branch of the provider?

**Comment by hakkurt** [comment]
I used official provider. (https://www.terraform.io/docs/providers/nsxt/index.html). I believe I need to use latest code in github

**Comment by annakhm** [comment]
Yes, this feature is not yet released, you'll need to compile the provider from master.
