### ISSUE TITLE
API rate limit reached

### ISSUE THREAD

**Issue by ywei2017** [terraform-providers/terraform-provider-nsxt#189]
Got the following error. I understand we can raise the limit on the nsx manager, but would think a rate limit on the nsxt provider would be beneficial.

Any thought or work along that line? Or raising the limit on the server is the only available choice?

`* restapi_object.infrastructure-outbound: restapi_object.infrastructure-outbound: Unexpected response code '429': {                     
    "module_name" : "common-services",                                                                                                  
    "error_message" : "Client 'admin' exceeded request rate of 100 per second",                                                         
    "error_code" : "102"                                                                                                                
}                                                                                                                                       
`

Thanks
Yansheng

**Comment by annakhm** [comment]
Hello @ywei2017, by default the provider should retry upon 429. You can specify retry parameters on the provider, f.e. increase min delay https://www.terraform.io/docs/providers/nsxt/index.html#retry_min_delay

**Comment by annakhm** [comment]
I'm closing this based on above comment, please reopen if issue still observed!
