### ISSUE TITLE
Resource nsxt_ns_group support for IPSet membership_criteria

### ISSUE THREAD

**Issue by robjw85** [terraform-providers/terraform-provider-nsxt#192]
We are trying to create ns groups's based on membership criteria of tags assigned to virtual machines and tags assigned to IPSets.

This resource currently does not support IPSets as membership criteria however the GUI does.

Error: expected membership_criteria.0.target_type to be one of [LogicalPort LogicalSwitch VirtualMachine], got IPSet

Running NSX-T Data Center 2.4.2

![ns_group](https://user-images.githubusercontent.com/43417961/66136246-c4d0a380-e5c0-11e9-858f-5afd91d9e0f5.png)

**Comment by annakhm** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/195
