### ISSUE TITLE
New release of nsxt provider

### ISSUE THREAD

**Issue by afritzler** [terraform-providers/terraform-provider-nsxt#197]
Hi,

is it possible to create a new release of the NSXT Terraform provider as we need those three changes #190, #191 and #196.

Regards,
Andreas

/cc @MartinWeindel @mandelsoft

**Comment by annakhm** [comment]
Hi @afritzler, we are hoping to release 1.1.2 in couple of weeks.

**Comment by annakhm** [comment]
Done
