### ISSUE TITLE
Question: how do I attach a VM to an existing NSX-T logical switch

### ISSUE THREAD

**Issue by vthinsel** [terraform-providers/terraform-provider-nsxt#206]
Hello,

I probably missed something in the provider documentation, but how do I attach a VM on an existing NST-T logical switch / segment ? logical switch are only resources in the provider, not data.
So far NSX-T provider is great for configuring deploying NSX-T, but now I need it as data for provisioning VMs. Is it part of the roadmap ?

Thanks.

**Comment by tvigneron** [comment]
Hello vthinsel,
You can put VM on top of NSX-T LS with the vSphere Provider.
The network resource allows you to get NSX-T network in the vCenter (opaque network) and use them to connect VM:
https://www.terraform.io/docs/providers/vsphere/d/network.html
Is that what you are looking for?

**Comment by vthinsel** [comment]
Thanks a lot for your answer, and yes this is what I was looking for !
Thanks again.

**Comment by vthinsel** [comment]
On the other hand, it looks to work only for NSX-V, not NSX-T. Will perform more tests but I guess I had alreay tried this. Will update with my findings.

**Comment by tvigneron** [comment]
This works for NSX-T
OpaqueNetwork for networks managed externally by features such as NSX

**Comment by vthinsel** [comment]
So I probably have something wrong somewhere :



```
> terraform apply
data.vsphere_datacenter.tfd_AT101DC: Refreshing state...
data.vsphere_tag_category.tfd_BUU: Refreshing state...
data.vsphere_tag_category.tfd_Environment: Refreshing state...
data.vsphere_network.tfd_InfraNetwork: Refreshing state...
data.vsphere_datastore.tfd_datastoreNFS01: Refreshing state...
data.vsphere_resource_pool.tfd_poolInfra: Refreshing state...
data.vsphere_compute_cluster.tfd_cluster: Refreshing state...
data.vsphere_virtual_machine.tfd_template_win2019: Refreshing state...
data.vsphere_virtual_machine.tfd_template_centos7: Refreshing state...
data.vsphere_tag.tfd_tagPROD: Refreshing state...
data.vsphere_tag.tfd_tagINFRA: Refreshing state...

Error: error fetching network: network 'at101-w01-nvds01-ls-10.122.4.254//24-Prod-Front-Docker' not found

  on AT1_SwarmCluster.tf line 113, in data "vsphere_network" "tfd_InfraNetwork":
 113: data "vsphere_network" "tfd_InfraNetwork" {
```

The tf portion : 

```
data "vsphere_network" "tfd_InfraNetwork" {
  #name          = nsxt_logical_switch.tfr_NSXTNetwork.display_name
  name          = "at101-w01-nvds01-ls-10.122.4.254/24-Prod-Front-Docker"
  datacenter_id = data.vsphere_datacenter.tfd_AT101DC.id
}
```

The segment; 
![image](https://user-images.githubusercontent.com/17785487/70789502-6e879a00-1d93-11ea-9983-65fe2d17c14c.png)


NSX-T version is 2.4.2.0.0.14269548 (will be upgraded to 2.4.3 soon also)

I can switch to debug and post them if ti can help

Thanks.

**Comment by vthinsel** [comment]
I sorted my issue. It was just a stupid problem with folder and / in the segment name.
Having  "/" in the segment name works fine if the segment is at the datacenter level
Having a "/" in the segment name doesnt work if the segment is placed into a network folder, which is strange as the / acts as a folder separator. I changed "/" for "_" in the segment name and now everything is OK.

**Comment by prabu28** [comment]
hi ,

i m getting the same error  
how do i force to pick the opaque type network only

can any one share a reference code to use an existing opaquenetwork ?

Error: error fetching network: path 'i-10.202.72.0_22-mn011h1t2-nvds1' resolves to multiple networks, Please specify

  on Windows.tf line 81, in data "vsphere_network" "network":
  81: data "vsphere_network" "network" {

**Comment by prabu28** [comment]
> I sorted my issue. It was just a stupid problem with folder and / in the segment name.
> Having "/" in the segment name works fine if the segment is at the datacenter level
> Having a "/" in the segment name doesnt work if the segment is placed into a network folder, which is strange as the / acts as a folder separator. I changed "/" for "_" in the segment name and now everything is OK.

@vthinsel  are u able to fix this issues
