### ISSUE TITLE
Declarative API supprt

### ISSUE THREAD

**Issue by wkleinhenz** [terraform-providers/terraform-provider-nsxt#213]
So i was wondering if/when support for the declarative api with be added, from what i understand thats the preference and would like to use that along with the simplified UI over the Adv Networking and security UI

**Comment by tvigneron** [comment]
Hello,
Ressources and datasources using the declarative API have been added a few days ago.
https://github.com/terraform-providers/terraform-provider-nsxt/tree/nsxt-policy-support
They are currently being tested and will be pushed on Hashicorp in the timeframe of next NSX release.
You can already get them by compiling the NSX-T Terraform Provider from the GitHub

**Comment by wkleinhenz** [comment]
oh ok i was unaware of that thanks for the quick response, ill close this
