### ISSUE TITLE
Unknown token path in nsxt-policy-support branch

### ISSUE THREAD

**Issue by walbertus** [terraform-providers/terraform-provider-nsxt#219]
This module is using nsxt-policy-support branch to use policy API.

### My module
```
data "nsxt_policy_edge_cluster" "EC_01" {
  display_name = "Cluster-01"
}

data "nsxt_policy_tier0_gateway" "T0_01" {
  display_name = "T0-Gateway-01"
}

resource "nsxt_policy_tier1_gateway" "T1_01" {
  description               = "T1 description"
  display_name              = "T1-Gateway-01"
  edge_cluster_path         = data.nsxt_policy_edge_cluster.EC_01.path
  failover_mode             = "NON_PREEMPTIVE"
  default_rule_logging      = "false"
  enable_firewall           = "true"
  enable_standby_relocation = "false"
  force_whitelisting        = "true"
  tier0_path                = data.nsxt_policy_tier0_gateway.T0_01.path
  route_advertisement_types = ["TIER1_STATIC_ROUTES", "TIER1_CONNECTED"]

  tag {
    scope = "${local.nsx_tag_scope}"
    tag   = "${local.nsx_tag}"
  }
}
```

### The problem

Unknown token: 4:31 IDENT data.nsxt_policy_edge_cluster.EC_01.path

It seems that it cannot resolve `path` from edge_cluster, it also happens to `path` in tier0 gateway. On tier0 gateway it also failed to resolve attribute `edge_cluster_path`.

I follow manual installation as stated here https://github.com/terraform-providers/terraform-provider-nsxt/tree/nsxt-policy-support#manual-installation

**Comment by annakhm** [comment]
Hello @walbertus, are you using terraform 0.12? This sample uses 0.12 syntax

**Comment by walbertus** [comment]
@annakhm yes I'm using v0.12.20 as it stated that `The current version of this provider requires Terraform v0.10.2 or higher to run.`

**Comment by walbertus** [comment]
Or is it only working on 0.11.7 because of this `The VMware supported version of the provider requires NSX version 2.2 onwards and Terraform 0.11.7.`?

**Comment by tvigneron** [comment]
Walbertus,  if you are using terraform 0.12 it should work.
What is your NSX-T version? It needs to be a version with Policy API.

**Comment by annakhm** [comment]
I'm guessing this can be formatting issue related to 0.12. Could you try reformatting/removing indentation?

**Comment by walbertus** [comment]
@tvigneron I'm using NSX-T 2.5.0

@annakhm I tried removing all indentation and reformat using `terraform fmt` and it works, thanks
