### ISSUE TITLE
nsxt-policy-support: missing nsxt_policy_ip_pool data source

### ISSUE THREAD

**Issue by MartinWeindel** [terraform-providers/terraform-provider-nsxt#226]
Since version v1.1.2 there is a datasource `nsxt_ip_pool`. But in the nsxt-policy-support branch the corresponding datasource `nsxt_policy_ip_pool`is missing. This prevents to lookup an IP pool by display name.

**Comment by annakhm** [comment]
Hi @MartinWeindel, you are right, we are adding this data source.

**Comment by annakhm** [comment]
Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/232
