### ISSUE TITLE
Creating nsxt_policy_dhcp_server resource fails with error

### ISSUE THREAD

**Issue by MartinWeindel** [terraform-providers/terraform-provider-nsxt#227]
On trying to create a resource of type nsxt_policy_dhcp_server

```
resource "nsxt_policy_dhcp_server" "dhcpserver" {
  display_name      = "test"
  edge_cluster_path = "${data.nsxt_policy_edge_cluster.EC.path}"
  server_addresses  = ["192.168.255.1/24"]
  lease_time        = 7200
}
```

this error is returned.

> Error:  Failed to create DhcpServer f967f88d-6fdb-4c07-84bb-cc258b2d55a4: Json de-serialization error: property server_addresses is unrecognized. (code 287)

Creating a DHCP server with the same values in the NSX-T UI works without problems.

NSX-T Version: 2.5.0.0.0.14663974

**Comment by annakhm** [comment]
Hi @MartinWeindel , nsxt_policy_dhcp_server resource is not supported with your NSX version: https://github.com/terraform-providers/terraform-provider-nsxt/blob/master/website/docs/r/policy_dhcp_server.html.markdown

**Comment by annakhm** [comment]
Same issue https://github.com/terraform-providers/terraform-provider-nsxt/issues/225
