### ISSUE TITLE
DHCP Server enforces gateway

### ISSUE THREAD

**Issue by David-VTUK** [terraform-providers/terraform-provider-nsxt#231]
I have a requirement for VM's to be multi-homed, but I only want one default gateway. According to https://www.terraform.io/docs/providers/nsxt/r/logical_dhcp_server.html the gateway property is required, but through the NSX-T CLI/API this is not the case:

![image](https://user-images.githubusercontent.com/5892615/74196365-fafbef00-4c54-11ea-958d-a6d6de91fa79.png)

Trying to specify a DHCP server without a gateway returns the following:

The argument "gateway_ip" is required, but no definition was found.

**Comment by annakhm** [comment]
Thanks for reporting this, fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/245
