### ISSUE TITLE
nsxt_vm_tags only applies to first interface

### ISSUE THREAD

**Issue by DH-Rancher** [terraform-providers/terraform-provider-nsxt#233]
Hi,

I have a VM, connected to two logical switches that I would like to tag the logical ports with.

```
data "vsphere_virtual_machine" "vm1" {
  name = "vsphere-nsxt-cluster-1"
  datacenter_id = data.vsphere_datacenter.dc.id
}
```

```
resource "nsxt_vm_tags" "vm1_tags" {
  instance_id = data.vsphere_virtual_machine.vm1.id

  tag {
    scope = "ncp/cluster_name"
    tag   = "terraform"
  }

  logical_port_tag {
    scope = "ncp/cluster_name"
    tag   = "terraform"
    
  }
}
```

When I check NSX-T, only the first interface has this applied:

![image](https://user-images.githubusercontent.com/57356014/74257469-cb98c100-4cec-11ea-8aa6-77a1efbd0fef.png)

This corresponds to the first interface that's shown in the VM config

![image](https://user-images.githubusercontent.com/57356014/74257521-df442780-4cec-11ea-91c1-2c1a265bf7a5.png)

Ideally, it would be nice to have the abilitiy to apply tags to specific interfaces, or at least, tag all interfaces associated with a VM.

**Comment by annakhm** [comment]
Thanks for reporting this. Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/235
