### ISSUE TITLE
Error creating nsxt_policy_security_policy

### ISSUE THREAD

**Issue by arcanelego** [terraform-providers/terraform-provider-nsxt#234]
Hi All,

I'm attempting to make a simple policy using only the required parameters but I get the following error.

### Error
```
Error: Failed to create Security Policy 745f7bbd-f47d-491c-872d-78554148d78d (failed to extract additional details due to [Expected a value of type 'IntegerValue', but received a value of type '*data.StringValue' Invalid field 'error_code' in structure 'com.vmware.nsx_policy.model.api_error'])

  on main.tf line 1, in resource "nsxt_policy_security_policy" "automon_test":
   1: resource "nsxt_policy_security_policy" "automon_test" {
```

### Resource definition:

```
resource "nsxt_policy_security_policy" "automon_test" {
    display_name = "app.automon"
    description  = "Test provisioned Security Policy"
    category     = "Application"
    locked       = false
    stateful     = true
    tcp_strict   = false
}
```

I've also tried importing an existing resource and I have a similar issue during the import

```
terraform import nsxt_policy_security_policy.dba default/0b8411c0-f6bc-11e9-96cd-1929accbdbaf                          
nsxt_policy_security_policy.dba: Importing from ID "default/0b8411c0-f6bc-11e9-96cd-1929accbdbaf"...
nsxt_policy_security_policy.dba: Import prepared!
  Prepared nsxt_policy_security_policy for import
nsxt_policy_security_policy.dba: Refreshing state... [id=0b8411c0-f6bc-11e9-96cd-1929accbdbaf]

Error: Failed to read Security Policy 0b8411c0-f6bc-11e9-96cd-1929accbdbaf (failed to extract additional details due to [Expected a value of type 'IntegerValue', but received a value of type '*data.StringValue' Invalid field 'error_code' in structure 'com.vmware.nsx_policy.model.api_error'])
```

### Environment

We are running NSX-T 2.5 (Version 2.5.0.0.0.14663974), so this could be the issue.

I'd appreciate any help.

**Comment by annakhm** [comment]
Hi @arcanelego, unfortunately NSX 2.5 sends out API errors in wrong format (message format does not match API spec, which causes golang SDK to fail in error parsing).
This issue will not exist with NSX 3.0. Meanwhile we'll look into exposing at least some error info, such as http code, for 2.5 as well.
In your case, I would suggest to check if other types of resources (such as group or service) can be created successfully.

**Comment by arcanelego** [comment]
Thanks For the update @annakhm i've actually managed to get this tested on Version 2.5.1.0.0.15314288 and I can create the resource as expected.

I can now continue (I have other issues but i'll open others). Did you want me to leave this open? Otherwise i'm happy to close.

**Comment by annakhm** [comment]
Thanks @arcanelego! Glad it works for you, closing this as you suggest
