### ISSUE TITLE
Cannot specify scope in criteria/condition of nsxt_policy_group

### ISSUE THREAD

**Issue by arcanelego** [terraform-providers/terraform-provider-nsxt#236]
Hi!

Just trying to create a policy group with the following code:

```
resource "nsxt_policy_group" "app_ns_group" {
    display_name = "tf-${var.app_name}"
    description  = "Terraform provisioned Group"

    criteria {
        condition {
            key         = "Tag"
            member_type = "VirtualMachine"
            operator    = "EQUALS"
            value       = var.app_name
        }
        condition {
            key         = "Tag"
            member_type = "VirtualMachine"
            operator    = "EQUALS"
            value       = var.env
        }
    }
}
```

In the GUI you can select a scope to target the scope of the tags but you can't specify a scope in the condition. 

Would be great to have this feature available.

**Comment by annakhm** [comment]
Hi @arcanelego, you can specify the scope within "value" attribute, in format "scope|tag", for example:

```
condition {
            key         = "Tag"
            member_type = "VirtualMachine"
            operator    = "EQUALS"
            value       = "color|green"
}
```

We will update docs to include this, thanks for pointing this out.

**Comment by arcanelego** [comment]
Awesome thank you, this works as expected.

**Comment by annakhm** [comment]
Docs updated with https://github.com/terraform-providers/terraform-provider-nsxt/pull/243
