### ISSUE TITLE
Logical Switch deletion dependencies

### ISSUE THREAD

**Issue by David-VTUK** [terraform-providers/terraform-provider-nsxt#237]
Compiling and testing the most recent commit appears to have 

```
	localVarOptionals["detach"] = true
```
omitted from /resource_nsxt_logical_switch.go

Which was originally merged in https://github.com/terraform-providers/terraform-provider-nsxt/pull/202/files by @annakhm 

If a logical switch has connected ports, Terraform will not delete them:

```
Error: Error during LogicalSwitch delete: Status: 400 , Body: {
  "httpStatus" : "BAD_REQUEST",
  "error_code" : 8402,
  "module_name" : "NsxSwitching service",
  "error_message" : "Unable to delete logical port with attachments of LogicalPort LogicalPort/95b4bd1e-3314-43ce-8691-f42d808615ea."
}
```

Unless this change was deliberate?

**Comment by annakhm** [comment]
Thank you for noticing this, this change was lost in a merge.
Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/239

**Comment by annakhm** [comment]
Fix merged
