### ISSUE TITLE
Enhancement for Policy Segment resource

### ISSUE THREAD

**Issue by raymonddejong** [terraform-providers/terraform-provider-nsxt#242]
Can we add the enhancement for the Policy Segment creation that you optionally can link a Named Teaming Policy to that segment? Prerequisite would be that that specific Named Teaming Policy has been added to the VLAN Transport Zone.

**Comment by annakhm** [comment]
Hi @raymonddejong, this was addressed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/270
