### ISSUE TITLE
Specify Interface for Tagging

### ISSUE THREAD

**Issue by David-VTUK** [terraform-providers/terraform-provider-nsxt#248]
Previous bug was fixed https://github.com/terraform-providers/terraform-provider-nsxt/issues/233 which addressed tags only applying to the first interface. However, with products like the NSX-T NCP CNI plugin for K8s, it requires *only* the logical port used to facilitate overlay traffic to be tagged, having all ports tagged causes issues with this.

**Comment by annakhm** [comment]
Hi @David-VTUK, this is solved on policy level with https://github.com/terraform-providers/terraform-provider-nsxt/pull/406
