### ISSUE TITLE
Deleting previously created interface tags results in HTTP 400

### ISSUE THREAD

**Issue by David-VTUK** [terraform-providers/terraform-provider-nsxt#249]
Compiling and using the latest committed version. Creation of logical port tags succeeds but deleting the same tag results in the following

```
Error: Error while updating tags on logical port a439ad06-64d1-49b4-a554-35f309711188: Status: 400 , Body: {
  "details" : "Field level validation errors: {required property attachment.context.vif_type is missing}",
  "httpStatus" : "BAD_REQUEST",
  "error_code" : 255,
  "module_name" : "common-services",
  "error_message" : "Field level validation errors: {required property attachment.context.vif_type is missing}"
}
```

**Comment by annakhm** [comment]
Hi @David-VTUK, I don't see the issue you report - could you please provide more details? Nsx version and tf config would help.

**Comment by DH-Rancher** [comment]
Apologies @annakhm for the delay - I think this is a false positive trying to overcome https://github.com/terraform-providers/terraform-provider-nsxt/issues/248. Ie deleting a tag I've manually deleted. Can be closed.

**Comment by David-VTUK** [comment]
Apologies @annakhm for the delay - I think this is a false positive trying to overcome #248. Ie deleting a tag I've manually deleted. Can be closed.

**Comment by annakhm** [comment]
Thanks @David-VTUK, closing.
