### ISSUE TITLE
Resource nsxt_vm_tags argument logical_port_tag

### ISSUE THREAD

**Issue by rogerscuall** [terraform-providers/terraform-provider-nsxt#309]
The resource `nsxt_vm_tags` has the argument `logical_port_tag`, the description is:
```
(Optional) A list of scope + tag pairs to associate with all logical ports that are automatically created for this VM.
```
It looks like that if a VM has two or more interfaces, it can have different tags on each logical port. So I would like to request the extension of this resource to do the same so each segment port can have a different tag for the same VM.

**Comment by annakhm** [comment]
Hi @rogerscuall, this is solved on policy level with https://github.com/terraform-providers/terraform-provider-nsxt/pull/406. This allows to specify tags per VM per segment.
