### ISSUE TITLE
Orphaned nsxt_policy_service resource exists even though TF says "destroyed"

### ISSUE THREAD

**Issue by neil-wwt** [terraform-providers/terraform-provider-nsxt#312]
# Summary
When the local name of a `nsxt_policy_service` resource is changed, TF says it will destroy and recreate it. When applied, TF reports it is destroyed but the resource still exists in UI afterwards. It is "orphaned" essentially. 

**It appears this only happens when the `nsxt_policy_service` resource is referenced by another resource as in the example below. When the `nsxt_policy_service` resource is not referenced anywhere else, the name change and subsequent destroy appear to happen as expected**

# Steps to reproduce
- Create "nsxt_policy_service" resource via terraform
- Use that resource in a `nsxt_policy_security_policy` resource
- Rename the local name (and change display name if you want)
- terraform apply
- Output will say "1 to create" and "1 to destroy"
- Check NSXT UI after apply. The service that should have been destroyed still exists.

# Expected Behavior
Resource is destroyed after apply is finished

# Actual Behavior
Resource still exists even though terraform thinks it has been destroyed

# Example Code
```
resource "nsxt_policy_security_policy" "MTWA-Policy" {
    display_name = "MTWA Policy"
    description  = "Firewall rules required by MTWA (provisioned by Terraform)"
    category     = "Application"
    locked       = false
    stateful     = true
    tcp_strict   = false
    
    rule {
      display_name       = "App to DB"
      source_groups      = []
      destination_groups = []
      action             = "ALLOW"
      logged             = true
      disabled           = false
      services           = [nsxt_policy_service.MTWA-MySQL-bar.path]

    }
}

resource "nsxt_policy_service" "MTWA-MySQL-bar" {
  description  = "Database connection (provisioned by Terraform)"
  display_name = "MTWA-MySQL"

  l4_port_set_entry {
    display_name      = "TCP3306"
    description       = "TCP port 3306 entry"
    protocol          = "TCP"
    destination_ports = [ "3306" ]
  }
}
```

In the above example, changing the local name `MTWA-MySQL-bar` will result in two services in NSXT, one in use, one orphaned.

Trace log attached. In the log, the change was `MTWA-MySQL-foo`  -> `MTWA-MySQL-bar`

**Comment by neil-wwt** [comment]
[trace.log](https://github.com/terraform-providers/terraform-provider-nsxt/files/4618678/trace.log)

In this log, the change was `MTWA-MySQL-foo` -> `MTWA-MySQL-bar`

**Comment by neil-wwt** [comment]
edited issue to reflect that it appears to only happen when the another resource references the resource being renamed (and thereby destroyed) 

In other cases, with different resources, TF throws an error that the resource is referenced else where. In the case described above, no such error is thrown.

**Comment by annakhm** [comment]
Thank you for reporting this! The error in service was indeed being swallowed. Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/321
