### ISSUE TITLE
Import fails on nsxt_ip_pool_allocation_ip_address

### ISSUE THREAD

**Issue by wilsonehusin** [terraform-providers/terraform-provider-nsxt#315]
## Scenario
I lost my `tfstate` and trying to recover the components. I would like to import the IP associated with the lost `tfstate` with:
```sh
terraform import nsxt_ip_pool_allocation_ip_address.inbound_ip 10.200.10.1
```

## Expected
IP to be added to my `tfstate`

## Actual
```
nsxt_ip_pool_allocation_ip_address.inbound_ip: Importing from ID "10.200.10.1"
nsxt_ip_pool_allocation_ip_address.inbound_ip: Import prepared!
  Prepared nsxt_ip_pool_allocation_ip_address for import
nsxt_ip_pool_allocation_ip_address.inbound_ip: Refreshing state... [id=10.200.10.1]

Error: Error obtaining pool id
```
([relevant line of code](https://github.com/terraform-providers/terraform-provider-nsxt/blob/master/nsxt/resource_nsxt_ip_pool_allocation_ip_address.go#L77))
## Notes
I have validated through `/api/v1/pools/ip-pools/:pool_id/allocations` that `10.200.10.1` is still allocated.

My terraform configuration:
```tf
data "nsxt_ip_pool" "ip_pool" {
  display_name = IP_POOL_NAME
}
resource "nsxt_ip_pool_allocation_ip_address" "inbound_ip" {
  ip_pool_id = data.nsxt_ip_pool.ip_pool.id
}
```

In a `tfstate` produced by `terraform apply`, I can see that `ip_pool_id` seem to match `:pool_id` that I used for validating allocation through HTTP API.

I imagine this might be a missing step to check for `nsxt_ip_pool.ip_pool`?

**Comment by annakhm** [comment]
Thanks for reporting this! Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/319
