### ISSUE TITLE
nsxt_policy_vlan_segment does not allow to use a range of vlan IDs

### ISSUE THREAD

**Issue by mdegrasse** [terraform-providers/terraform-provider-nsxt#338]
can't use range 0-4094 as vlan id (typically used to create trunk segments).

This is permitted in the GUI and via policy API but not working in terraform

resource "nsxt_policy_vlan_segment" "S10000-TRUNK-UPLINK6" {
  display_name        = "S10000-TRUNK-UPLINK6"
  description         = "Trunk VLAN for Edge Hosts"
  transport_zone_path = data.nsxt_policy_transport_zone.tz-vlan.path
  vlan_ids            = ["0-4094"]
  advanced_config { uplink_teaming_policy = "FailoverOnly" }
}

Returns error -> Error: cannot convert 0-4094 to int

**Comment by annakhm** [comment]
Thanks for reporting this! Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/342
