### ISSUE TITLE
Route redistribution for T0 router not available in nsxt_policy_tier0_gateway

### ISSUE THREAD

**Issue by dmnt3d** [terraform-providers/terraform-provider-nsxt#347]
Hello, 
In nsx-t 3.0, route redistribution for tier0 routers is now a named list which allows you to have router map per item.

From the docs, there is no way for you to set route-redistribution in tier0 routers. This option is only available right now in tier1 router.

Is this by design?
THank you.
Error: Unsupported argument

  on main.tf line 80, in resource "nsxt_policy_tier0_gateway" "dr-t0":
  80:   route_advertisement_types = [

An argument named "route_advertisement_types" is not expected here.

**Comment by annakhm** [comment]
Thanks for filing this @dmnt3d. Fixed with https://github.com/terraform-providers/terraform-provider-nsxt/pull/363.
