### ISSUE TITLE
Terraform crash while creating logical port

### ISSUE THREAD

**Issue by ashishg29** [terraform-providers/terraform-provider-nsxt#35]
Terraform Version
Terraform v0.11.7

Provider Version

├── provider.nsxt 1.0.0
└── provider.vsphere 1.3.3
go version go1.9.2 linux/amd64

stack@no:~/go/bin$ terraform providers

Affected Resource(s)
Please list the resources as a list, for example:
nsxt_logical_port

Terraform Configuration Files
Debug Output
:

nsxt_logical_port.LP1.69: unexpected EOF
2018/05/17 08:48:18 [TRACE] [walkApply] Exiting eval tree: nsxt_logical_port.LP1[69]
2018/05/17 08:48:18 [TRACE] root: eval: *terraform.EvalApplyPost
2018/05/17 08:48:18 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
Panic Output
https://gist.github.com/ashishg29/9af88f467dd3c13b866a11bba3f0c529

Expected Behavior
What should have happened?
Proper reason for the crash should be provided for the user to debug the issue.
And during plan itself the check should be added.

Actual Behavior
What actually happened?
The template work in past multiple time but suddenly if fails with terraform crash error  and this issue is not always seen.

Steps to Reproduce
Attaching the main.tf
https://gist.github.com/ashishg29/9af88f467dd3c13b866a11bba3f0c529
Please list the steps required to reproduce the issue, for example:
1.
./terraform apply -parallelism=100

**Comment by annakhm** [comment]
Not observed on latest
