### ISSUE TITLE
BGP Neighbor timers

### ISSUE THREAD

**Issue by pokepoke81** [terraform-providers/terraform-provider-nsxt#385]
While troubleshooting an issue with BGP peering on a tier0, VMware told me that the keep alive and hold down timers have to be a multiple of 3. The documentation for BGP neighbors are not a multiple of three. Please change the documentation if this is correct.

**Comment by tvigneron** [comment]
Hello,
There is no hard requirement in the NSX-T UI or API to have multiples of 3.
This is not part of the BGP configuration documentations:
 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.3/com.vmware.nsxt.admin.doc/GUID-4BC07C6A-DC62-496B-A6A9-7219ACF5AC7B.html 
Design documents recommending timers like for instance (https://docs.vmware.com/en/VMware-Validated-Design/4.3/com.vmware.vvd.sddc-nsxt-design.doc/GUID-BD316E92-665D-45B1-9762-036ED2DA9A41.html?hWord=N4IghgNiBcIEIHEAKACALgSwLYFMBOIAvkA) exist but the Terraform documentation is not the place for this.

**Comment by tvigneron** [comment]
To my knowledge nothing prevents you from putting a keep alive / hold on timers which are not multiple of 3 (like 10/40 for instance)

**Comment by pokepoke81** [comment]
I've asked the VMware support tech to provide more information on why 3. I'll update when he responds. Changing those timers fixed the peering issue, so something is up.

**Comment by pokepoke81** [comment]
Well the response back wasn't helpful:

"Like I said during our call, this isn't documented and a ticket with our developers has been opened with our developers to address the issue by either a code fix, input validation and/or documentation updates."

**Comment by tvigneron** [comment]
Hello Pokepoke81, do you mind sending me your customer information (name of the company, #SR id) by mail. My mail is tvigneron@vmware.com.
As I said I am not aware of such limitation, please provide the informations and I'll me circle back
