### ISSUE TITLE
Can't use dot notation for ASN numbers

### ISSUE THREAD

**Issue by mdegrasse** [terraform-providers/terraform-provider-nsxt#402]
Need to be able to use dot notation for ASN numbers

IE 64530.197 has to be entered as 4229038277 and is very annoying

resource "nsxt_policy_bgp_neighbor" "T0-if-uplink1-bgp" {
  display_name          = "T0-if-uplink1-bgp"
  description           = "BGP to whatever"
  bgp_path              = nsxt_policy_tier0_gateway.T0.bgp_config.0.path
  allow_as_in           = false
  graceful_restart_mode = "HELPER_ONLY"
  hold_down_time        = 15
  keep_alive_time       = 5
  neighbor_address      = "10.189.1.17"
  remote_as_num         = "4229038277" // --> NEED THIS TO WORK -- > "64530.197"
  source_addresses      = [ "10.189.1.18" ]//nsxt_policy_tier0_gateway_interface.T0-if-uplink1.subnets
  lifecycle {
    ignore_changes = [ remote_as_num ]
  }
}

**Comment by annakhm** [comment]
Thanks for filing this, fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/405
