### ISSUE TITLE
access_log_enabled property on nsxt_lb_tcp_virtual_server causes failures

### ISSUE THREAD

**Issue by DRuggeri** [terraform-providers/terraform-provider-nsxt#94]
It seems no matter what values I plug in, the system always kicks back an error about access_log_enabled property being set, but not expected by the API.

````
* nsxt_lb_tcp_virtual_server.test-vserver: Error during LbVirtualServer create: Status: 400 , Body: {
  "httpStatus" : "BAD_REQUEST",
  "error_code" : 287,
  "module_name" : "common-services",
  "error_message" : "Json de-serialization error: property access_log_enabled is unrecognized."
}
````

Indeed, when browsing the swagger spec for NSX-T API, this property didn't get added until 2.2 (I'm using 2.1). Is it intended for this provider to be only 2.2+ compatible?

**Comment by DRuggeri** [comment]
Also noticed the change between 2.1 -> 2.2 with the rename of `port` as a string (possibly a single integer or a range) to `ports` which is a list of the same.

This boils down to the interactions between `vendor/github.com/vmware/go-vmware-nsxt/loadbalancer/lb_virtual_server.go` and `nsxt/resource_nsxt_lb_*_virtual_server.go` files in addition to the API versioning.

**Comment by annakhm** [comment]
Hi @DRuggeri, thanks for filing this!
Yes the provider expects 2.2.x backend (as stated in README). We might be able to address the access_log_enabled issue if it helps, but "port to ports" change is more challenging to support.
